### ISSUE TITLE
Choose Different Indicator For Selected Variant

### ISSUE THREAD

**Issue by emersonlebleu** [iobio/sv.iobio#107]
Currently the selected variant turns yellow. There needs to be some other way to indicate this. Maybe make it taller, maybe add a symbol or a box around it something like that.

**Comment by chmille4** [comment]
A couple more ideas to distinguish the selected variant
1. Someone mentioned to lower the opacity of all other variants
2. Add a prominent box-shadow/elevation to the selected variant
