### ISSUE TITLE
Allow "Toggle Off" of non associated genes

### ISSUE THREAD

**Issue by emersonlebleu** [iobio/sv.iobio#109]
Allow the user to toggle off the genes that aren't associated. Also maybe add a little note that says how many are "hidden" in an area.

**Comment by chmille4** [comment]
The note could be used as the toggle. In mosaic we do this for lists that have extra data that we hide by default. Here if you click the blue text then those 156 additional genes will be added to the list and become scrollable
<img width="385" alt="Screen Shot 2024-11-21 at 11 39 29 AM" src="https://github.com/user-attachments/assets/b5b95095-403c-4f7d-9344-d12acc430da1">

**Comment by emersonlebleu** [comment]
I totally like this strategy! thanks for the suggestion, I'll just need to add that show less button.

**Comment by emersonlebleu** [comment]
Added a message similar to Chase's suggestion that hides non-affiliated genes if there are genes of interest or phenotype related genes available. It allows a click so that the user can toggle this option on/off.
