### ISSUE TITLE
Filter on genotype

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/sv.iobio#45]
An input vcf may have multiple samples and we need to handle these:
1. If you only choose one sample, we need to show only those SVs that are present in the sample of choice
2. If the vcf has multiple samples, then the user should be able to choose which samples they want to view

Gene.iobio does this, so you can talk to Tony / Steph, but basic thoughts:
1. When a vcf file is supplied, parse the header - `bcftools view -h <VCF> | tail -1`). This will give the samples in the vcf file. Provide these as options to the user for which samples they want to view
2. When showing variants in SV.iobio for a sample, make sure you only show variants present in the sample in their track. You can look at how gene.iobio does this, but `bcftools view -s <SAMPLE> <VCF>` will filter out the variants to just those present for the specified sample

**Comment by emersonlebleu** [comment]
This is completed with the last merge. There is now a choice in file loading workflow for the user.
