### ISSUE TITLE
What is the gene count in the variant list?

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/sv.iobio#48]
The list of variants had a gene count next to them. I assume this is the number of genes this variant spans? Is that true? Some span a lot (e.g. 2,580) which seem very high. That's ~10% of all genes. My guess is we're including transcripts etc? Anyway need to clarify

**Comment by emersonlebleu** [comment]
This has been somewhat addressed over iterations and is going to be covered again in more specific re-works given the meeting on the 20th. I'll try to get better labeling etc.
