### ISSUE TITLE
What does patient phenotypes do?

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/sv.iobio#49]
Input some HPO terms and the gene count next to a variant changes to a percentage. What does this represent? Also, it would be good to think through what we show here. Could I see how many HPO associated genes each variant spans? Which genes are they etc?

**Comment by AlistairNWard** [comment]
I clicked on the percentage and got data! It wasn't clear it was clickable, no loading button etc.

This is clearly just polish, but I'm just documenting what I see!

**Comment by emersonlebleu** [comment]
I did a little bit with this this morning because I was looking at it. So far just making it more understandable and visually appealing.
