### ISSUE TITLE
Zoom Increment/Decrement

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/sv.iobio#65]
I'm looking at a variant in 3 samples and there are a few variants in each sample, some of which fill the full width of the view. It would be useful to be able to zoom out for all samples.

<img width="1122" alt="Screenshot 2024-08-03 at 10 15 38" src="https://github.com/user-attachments/assets/ef83db6b-cc8c-40f2-9280-e39342bde6e5">

**Comment by emersonlebleu** [comment]
Added a zoom increment/decrement button option. We may need to decide about the amount... right now it is scaled to .2 of original zoom area.
